### ISSUE TITLE
"土" or "也" 都找不到 "地"

### ISSUE THREAD

**Issue by SCgeeker** [g0v/z0y#2]
如題, 很多raw data裡只有GT碼的有類似問題

**Comment by yapcheahshen** [comment]
4510f553db4cfae6da3718ec0642fb299143c59d 解決「天地不容」的問題
node_modules/idsdata/normalize_todo.txt 按部件頻次排序，參考node_modules/idsdata/rawdata.txt 看出字形，決定正規部件，填寫 node_modules/idsdata/variant.js ，就可以常用部件搜尋到異體部件。
如「土」可找到「土旁」。
